services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: storyflux
      POSTGRES_USER: storyflux
      POSTGRES_DB: storyflux
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: unless-stopped
    ports: ["6379:6379"]
volumes:
  pgdata:
